# Generated by Django 3.2.8 on 2021-10-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlsxproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xlsxproducts', to='xlsxproducts.xlsxproduct'),
        ),
    ]
