# Generated by Django 3.2.8 on 2021-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cookie_value',
            field=models.CharField(default='4fOsqMaFq#!9SANsf&AIBRigg8ptdHxxiI%BMvP6tdzi7Av864', max_length=50),
        ),
    ]
