# Generated by Django 3.2.8 on 2021-10-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211019_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
